# permissions for end users to view pubsubsubscriptiontemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pubsubsubscriptiontemplate-viewer-role
rules:
- apiGroups:
  - config-connector-templater.slamdev.net
  resources:
  - pubsubsubscriptiontemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config-connector-templater.slamdev.net
  resources:
  - pubsubsubscriptiontemplates/status
  verbs:
  - get
