# permissions for end users to edit pubsubsubscriptiontemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pubsubsubscriptiontemplate-editor-role
rules:
- apiGroups:
  - config-connector-templater.slamdev.net
  resources:
  - pubsubsubscriptiontemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config-connector-templater.slamdev.net
  resources:
  - pubsubsubscriptiontemplates/status
  verbs:
  - get
