# permissions for end users to view pubsubtopictemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pubsubtopictemplate-viewer-role
rules:
- apiGroups:
  - config-connector-templater.slamdev.net
  resources:
  - pubsubtopictemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config-connector-templater.slamdev.net
  resources:
  - pubsubtopictemplates/status
  verbs:
  - get
