# permissions for end users to edit pubsubtopictemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pubsubtopictemplate-editor-role
rules:
- apiGroups:
  - config-connector-templater.slamdev.net
  resources:
  - pubsubtopictemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config-connector-templater.slamdev.net
  resources:
  - pubsubtopictemplates/status
  verbs:
  - get
