apiVersion: config-connector-templater.slamdev.net/v1alpha1
kind: PubSubTopicTemplate
metadata:
  name: notifications
  namespace: team1
  annotations:
    service-name: super-service
spec:
  resourceID: "{{ .metadata.namespace }}.{{ index .metadata.annotations "service-name" }}.{{ .metadata.name }}"
