name: build

on:
  push:
    branches:
      - main
    tags:
      - '!*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: make build test
