name: release

on:
  push:
    branches:
      - '!*'
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u slamdev --password-stdin
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: |
          export RELEASE_VERSION="${GITHUB_REF##*/}"
          make docker-build docker-push VERSION="${RELEASE_VERSION}"
